### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by skasli** [tanersener/flutter-ffmpeg#97]
**Description**
Getting missing plugin exception when I try to run FlutterFFmpeg.executeWithArguments.

**Repo**
https://skasli@bitbucket.org/skasli/video-convert-test.git

**Current behavior**
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method executeFFmpegWithArguments on channel flutter_ffmpeg))

**Logs**
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
D/EGL_emulation(13922): eglMakeCurrent: 0xd6a1a360: ver 2 0 (tinfo 0xd6a0f800)
I/OpenGLRenderer(13922): Davey! duration=773ms; Flags=1, IntendedVsync=413678954962390, Vsync=413678954962390, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=413678958371700, AnimationStart=413678971763800, PerformTraversalsStart=413678971906100, DrawStart=413679640132300, SyncQueued=413679641947900, SyncStart=413679646005600, IssueDrawCommandsStart=413679648049200, SwapBuffers=413679676053100, FrameCompleted=413679732687200, DequeueBufferDuration=14802000, QueueBufferDuration=267000,
I/Choreographer(13922): Skipped 46 frames!  The application may be doing too much work on its main thread.
I/eo_convert_tes(13922): NativeAlloc concurrent copying GC freed 1140(134KB) AllocSpace objects, 0(0B) LOS objects, 57% free, 1135KB/2671KB, paused 1.459ms total 200.991ms
D/EGL_emulation(13922): eglMakeCurrent: 0xd6a1a2a0: ver 2 0 (tinfo 0xd6a0f7c0)
I/flutter (13922): [-i, /storage/emulated/0/Download/3d406930-1cc0-11ea-f534-e9cda6d236c4.MOV, -c:v, mpeg4, -b:v, 500K, -filter:v, scale=960x540, /data/user/0/com.wingding.wingdingapp/cache/convertVideoTemp/3d406930-1cc0-11ea-f534-e9cda6d236c5.mp4]

**Environment**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18363.592], locale tr-TR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.41.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by tanersener** [comment]
`0.2.9` includes a bug which causes MissingPluginException in iOS. It is reported in #94 and fixed in `0.2.10`. Can you please use `0.2.10`?

Btw, your application works on my test environment. 

```
INFO: ffmpeg version git-2020-01-14-b70229b9e
INFO:  Copyright (c) 2000-2020 the FFmpeg developers
FFmpeg exited with rc: 1
INFO:
INFO:   built with Apple clang version 11.0.0 (clang-1100.0.33.16)
INFO:   configuration: --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk --prefix=/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-apple-darwin/ffmpeg --enable-version3 --arch=x86_64 --cpu=x86_64 --target-os=darwin --ar=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar --cc=clang --cxx=clang++ --as='clang -arch x86_64 -target x86_64-ios-darwin -march=x86-64 -msse4.2 -mpopcnt -m64 -mtune=intel -DMOBILE_FFMPEG_X86_64 -Wno-unused-function -Wno-deprecated-declarations -fstrict-aliasing -DIOS -DMOBILE_FFMPEG_BUILD_DATE=20200114 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -O2 -mios-simulator-version-min=12.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include' --ranlib=/Applications/Xcode.app/Contents/Developer/Toolchain<…>
flutter: FFmpeg process exited with rc 1
INFO:   libavutil      56. 38.100 / 56. 38.100
INFO:   libavcodec     58. 65.102 / 58. 65.102
INFO:   libavformat    58. 35.101 / 58. 35.101
INFO:   libavdevice    58.  9.103 / 58.  9.103
INFO:   libavfilter     7. 70.101 /  7. 70.101
INFO:   libswscale      5.  6.100 /  5.  6.100
INFO:   libswresample   3.  6.100 /  3.  6.100
ERROR: /storage/emulated/0/Download/3d406930-1cc0-11ea-f534-e9cda6d236c4.MOV: No such file or directory
```

**Comment by skasli** [comment]
**Thanks** for the answer.
I updated to `0.2.10` but still getting error. I running with Xiaomi Mi6 and Android 10 emulator on Windows 10.

```I/flutter (15590): [-i, /storage/emulated/0/Download/3d406930-1cc0-11ea-f534-e9cda6d236c4.MOV, -c:v, mpeg4, -b:v, 500K, -filter:v, scale=960x540, /data/user/0/com.wingding.wingdingapp/cache/convertVideoTemp/3d406930-1cc0-11ea-f534-e9cda6d236c5.mp4]
E/flutter (15590): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method executeFFmpegWithArguments on channel flutter_ffmpeg)
E/flutter (15590): #0      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:314
E/flutter (15590): <asynchronous suspension>
E/flutter (15590): #1      FlutterFFmpeg.executeWithArguments 
package:flutter_ffmpeg/flutter_ffmpeg.dart:360
E/flutter (15590): <asynchronous suspension>
E/flutter (15590): #2      _MyHomePageState._incrementCounter 
package:video_convert_test/main.dart:64
E/flutter (15590): <asynchronous suspension>
E/flutter (15590): #3      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:654
E/flutter (15590): #4      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:729

**Comment by tanersener** [comment]
But I can't reproduce this error with your test app. I tested it myself and it worked for me. Posted the logs in my previous message. Can you try cloning your application into another directory and testing it from there?

By the way, there are other reasons that cause `MissingPluginException`. Can you google about them and try suggestions listed there?
